language: python
sudo: enabled
python:
  - 3.6.1
env:
  - FLASK=0.12  # recent Flask
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: nosetests test/tests.py --with-coverage --cover-package=test && coverage report

after_success: coveralls
    

