"""empty message

Revision ID: 05c97b2583c3
Revises: b51ea33e1dc1
Create Date: 2018-01-05 02:18:46.946497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c97b2583c3'
down_revision = 'b51ea33e1dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventlists', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eventlists', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eventlists', type_='foreignkey')
    op.drop_column('eventlists', 'created_by')
    # ### end Alembic commands ###
