"""empty message

Revision ID: 194e5b06659b
Revises: 019e5200cb79
Create Date: 2018-02-03 00:47:26.580461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194e5b06659b'
down_revision = '019e5200cb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blacklist_tokens', ['id'])
    op.create_unique_constraint(None, 'event_category', ['id'])
    op.alter_column('users', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'event_category', type_='unique')
    op.drop_constraint(None, 'blacklist_tokens', type_='unique')
    # ### end Alembic commands ###
