"""empty message

Revision ID: 30e8144bb535
Revises: 5f9828ca4eb2
Create Date: 2018-01-05 00:17:00.746322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e8144bb535'
down_revision = '5f9828ca4eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventlists', sa.Column('imageUrl', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventlists', 'imageUrl')
    # ### end Alembic commands ###
