"""empty message

Revision ID: 35cc173a4c89
Revises: 90e937151148
Create Date: 2018-01-25 13:06:08.064672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35cc173a4c89'
down_revision = '90e937151148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event_category', ['id'])
    op.drop_constraint('event_category_event_cartegory_fkey', 'event_category', type_='foreignkey')
    op.drop_column('event_category', 'event_cartegory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_category', sa.Column('event_cartegory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_category_event_cartegory_fkey', 'event_category', 'eventlists', ['event_cartegory'], ['id'])
    op.drop_constraint(None, 'event_category', type_='unique')
    # ### end Alembic commands ###
