"""empty message

Revision ID: 406bcf5c0f64
Revises: 35d2b0d0bc74
Create Date: 2018-01-25 15:14:47.373289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406bcf5c0f64'
down_revision = '35d2b0d0bc74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blacklist_tokens', ['id'])
    op.create_unique_constraint(None, 'event_category', ['id'])
    op.add_column('eventlists', sa.Column('category', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventlists', 'category')
    op.drop_constraint(None, 'event_category', type_='unique')
    op.drop_constraint(None, 'blacklist_tokens', type_='unique')
    # ### end Alembic commands ###
