"""empty message

Revision ID: 65239bc08fea
Revises: 1b96e9f041ad
Create Date: 2018-01-23 13:16:21.644075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65239bc08fea'
down_revision = '1b96e9f041ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blacklist_tokens', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blacklist_tokens', type_='unique')
    # ### end Alembic commands ###
