"""empty message

Revision ID: e42e0038a2b8
Revises: 406bcf5c0f64
Create Date: 2018-01-25 15:30:27.432416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42e0038a2b8'
down_revision = '406bcf5c0f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventlists', sa.Column('event_category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eventlists', 'event_category', ['event_category'], ['id'])
    op.drop_column('eventlists', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventlists', sa.Column('category', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'eventlists', type_='foreignkey')
    op.drop_column('eventlists', 'event_category')
    # ### end Alembic commands ###
