"""empty message

Revision ID: e8a248277e33
Revises: 3d6cd2f92d19
Create Date: 2018-01-16 12:41:07.934796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a248277e33'
down_revision = '3d6cd2f92d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blacklist_tokens', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blacklist_tokens', type_='unique')
    # ### end Alembic commands ###
